---
- name: OCP | Update OS | Include Tasks for Enable Excluders
  include_tasks: tasks/enable-excluders.yml

- name: OCP | Update OS | Any package updates required?
  command: 'yum check-update'
  args:
    warn: no
  register: packages_need_update_result
  changed_when: packages_need_update_result.rc == 100
  failed_when: packages_need_update_result.rc != 0 and packages_need_update_result.rc != 100

- name: OCP | Update OS | Include Tasks for Masters
  include_tasks: tasks/masters-os-update-and-upgrade.yml
  when: inventory_hostname in groups['masters']

- name: OCP | Update OS | Include Tasks for Nodes
  include_tasks: tasks/nodes-os-update-and-upgrade.yml
  when: inventory_hostname not in groups['masters']
