---
- name: OCP | Unschedule Node
  command: "oc adm manage-node {{ inventory_hostname }} --schedulable=false"

- name: OCP | Drain Node
  command: "oc adm drain {{ inventory_hostname }} --force --delete-local-data --ignore-daemonsets"
