---
- name: OCP | Stop Application Nodes Services
  hosts: app-nodes
  tasks:
    - name: Stop OpenShift Node
      service:
        name: atomic-openshift-node
        state: stopped

- name: OCP | Stop Infrastructure Nodes Services
  hosts: infra-nodes
  tasks:
    - name: Stop OpenShift Node
      service:
        name: atomic-openshift-node
        state: stopped

- name: OCP | Stop Master Nodes Services
  hosts: masters
  tasks:
    - name: Stop OpenShift Node
      service:
        name: atomic-openshift-node
        state: stopped

    - name: Stop OpenShift Master API
      service:
        name: atomic-openshift-master-api
        state: stopped

    - name: Stop OpenShift Master Controller
      service:
        name: atomic-openshift-master-controllers
        state: stopped

    - name: Stop ETCD
      service:
        name: etcd
        state: stopped

- name: OCP | Reboot Master Nodes Hosts
  hosts: masters
  tasks:
    - include_tasks: tasks/reboot.yml

- name: OCP | Reboot Infrastructure Nodes Hosts
  hosts: infra-nodes
  tasks:
    - include_tasks: tasks/reboot.yml

- name: OCP | Reboot Application Node Hosts
  hosts: app-nodes
  tasks:
    - include_tasks: tasks/reboot.yml
