---
- name: OCP | Stop Application Nodes Services
  hosts: app-nodes
  tasks:
    - name: Stop OpenShift App Node Services
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - atomic-openshift-node
        - docker

- name: OCP | Stop Infrastructure Nodes Services
  hosts: infra-nodes
  tasks:
    - name: Stop OpenShift Infra Node Services
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - atomic-openshift-node
        - docker

- name: OCP | Reboot Master Nodes Hosts
  hosts: masters
  tasks:
    - include_tasks: tasks/reboot.yml
      vars:
        reboot_only_if_needed: False

- name: OCP | Reboot Infrastructure Nodes Hosts
  hosts: infra-nodes
  tasks:
    - include_tasks: tasks/reboot.yml
      vars:
        reboot_only_if_needed: False

- name: OCP | Reboot Application Node Hosts
  hosts: app-nodes
  tasks:
    - include_tasks: tasks/reboot.yml
      vars:
        reboot_only_if_needed: False
