---
- name: OCP | Rolling Reboot Hosts
  hosts: all
  gather_facts: True
  tasks:
  - name: OCP | Rolling Reboot Hosts | Set facts
    set_fact:
      openshift_oc_tools_host: "{{ groups['masters'][0] }}"

- name: OCP | Rolling Reboot Hosts | Masters
  hosts: masters
  gather_facts: False
  serial: 1
  tasks:
  - name: OCP | Rolling Reboot Hosts | Masters | Include Tasks
    include_tasks: tasks/ocp-host-reboot.yml

- name: OCP | Rolling Reboot Hosts | Infra Nodes
  hosts: infra-nodes
  gather_facts: False
  serial: 1
  tasks:
  - name: OCP | Rolling Reboot Hosts | Infra Nodes | Determine services
    set_fact:
      openshift_services:
      - atomic-openshift-node
      - docker
    when: openshift_services is not defined

  - name: OCP | Rolling Reboot Hosts | Infra Nodes | Include Tasks
    include_tasks: tasks/ocp-host-reboot.yml

- name: OCP | Rolling Reboot Hosts | App Nodes
  hosts: app-nodes
  gather_facts: False
  serial: 1
  tasks:
  - name: OCP | Rolling Reboot Hosts | App Nodes | Determine services
    set_fact:
      openshift_services:
      - atomic-openshift-node
      - docker
    when: openshift_services is not defined

  - name: OCP | Rolling Reboot Hosts | App Nodes | Include Tasks
    include_tasks: tasks/ocp-host-reboot.yml
