---
- name: OCP | Rolling Restart Services
  hosts: all
  gather_facts: True
  tasks:
  - name: OCP | Rolling Restart Services | Set facts
    set_fact:
      openshift_oc_tools_host: "{{ groups['masters'][0] }}"

- name: OCP | Rolling Restart Services | Masters
  hosts: masters
  gather_facts: False
  serial: 1
  tasks:
  - name: OCP | Rolling Restart Services | Masters | Include Tasks
    include_tasks: tasks/ocp-services-reboot/masters.yml

- name: OCP | Rolling Restart Services | Infra Nodes
  hosts: infra-nodes
  gather_facts: False
  serial: 1
  tasks:
  - name: OCP | Rolling Restart Services | Infra Nodes | Determine services
    set_fact:
      openshift_services:
      - atomic-openshift-node
      - docker
    when: openshift_services is not defined

  - name: OCP | Rolling Restart Services | Infra Nodes | Include Tasks
    include_tasks: tasks/ocp-services-reboot/nodes.yml

- name: OCP | Rolling Restart Services | App Nodes
  hosts: app-nodes
  gather_facts: False
  serial: 1
  tasks:
  - name: OCP | Rolling Restart Services | App Nodes | Determine services
    set_fact:
      openshift_services:
      - atomic-openshift-node
      - docker
    when: openshift_services is not defined

  - name: OCP | Rolling Restart Services | App Nodes | Include Tasks
    include_tasks: tasks/ocp-services-reboot/nodes.yml
