---
# ensure gluster is healthy before stopping another node
- include_role:
    name: openshift_storage_glusterfs_cluster_health

- name: OCP | Include Tasks for Unschedule and Drain
  import_tasks: tasks/unschedule-and-drain.yml
  delegate_to: "{{ openshift_oc_tools_host }}"

- name: OCP | Update OS | Restart Master API and Controllers
  include_tasks: tasks/restart_master_services.yml

- include_tasks: tasks/wait-for-node-ready.yml

- name: OCP | Schedule Node
  command: "oc adm uncordon {{ inventory_hostname }}"
  delegate_to: "{{ openshift_oc_tools_host }}"
